### ISSUE TITLE
Issue on page /content/Intro/demo-Intro.html

### ISSUE THREAD

**Issue by dbthe1** [physics-chalmers/tif285#10]
There is an error in the code that makes it so that the first 42 data entries are missing from the Masses DataFrame.
The reason for this is that infile is an iterator and after you show the first 42 lines of it the iterator is pointing to the 43:rd line. So when you start importing the file into Masses it is already at line 43 and continues from there. You need to either remove showing the first 42 lines or do a new: infile = open(data_path("MassEval2016.dat"),'r')  after you have done that to start the iterator from the beginning again.

**Comment by cforssen** [comment]
Thank you!
Indeed, infile is an iterator. It is better to do these early file explorations within a `with` block to keep it as a local iterator. Fixed in commit 9a894b661d8d54764469a594872262a3ad407ea8
Note, however, that the liquid drop model does not work very well for the lightest elements so the bug actually worked in the model's favor...
