### ISSUE TITLE
Issue on page /content/LinearRegression/ModelValidation.html

### ISSUE THREAD

**Issue by othim** [physics-chalmers/tif285#6]
Hi! Testing the issue function!

For me, it feels like the variable \tilde{y} should be a random variable.

> Furthermore, the function 𝑓 is not a stochastic variable, idem for 𝑦̃ .

/Oliver

**Comment by cforssen** [comment]
Thank you. Yes, otherwise the variance of model realizations (the second term in the equation for $\mathbb{E}[(y-\tilde{y})^2]) should be always zero, and it does in general not make sense to talk about expectation values. 
Fixed in
commit af73f7f5b4e1cf4221b64f2c7ba929ca2ae579e4
and will appear in the next build.
